# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email_id', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('age', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('level', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'signup',
                'managed': False,
            },
        ),
    ]
