# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180316_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainersignup',
            old_name='trainer_id',
            new_name='trainer_code',
        ),
    ]
