# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180319_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_code', models.CharField(max_length=45)),
                ('expriy_date', models.DateTimeField(blank=True, null=True)),
                ('userper_user', models.IntegerField()),
            ],
            options={
                'db_table': 'promocode',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='trainersession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trainersignup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usersignup',
            options={'managed': False},
        ),
    ]
