# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180319_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={},
        ),
    ]
