# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180319_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='userper_user',
            new_name='useper_user',
        ),
    ]
