# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180319_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='useper_user',
        ),
    ]
