# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_promocode_useper_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='userper_user',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
