# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180319_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='numberof_users',
            new_name='maxuse_peruser',
        ),
    ]
