# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180319_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='expriy_date',
            new_name='expiry_date',
        ),
    ]
